import type { PlateState } from "../../src/registry.ts";

/** Development samples and source locations; never part of the public package. */
export const PLATE_METADATA = {
  AK: { name: "Alaska", file: "AlaskaPlate.tsx", sample: "ABC123" },
  AL: { name: "Alabama", file: "AlabamaPlate.tsx", sample: "1AB2345" },
  AR: { name: "Arkansas", file: "ArkansasPlate.tsx", sample: "ABC12D" },
  AZ: { name: "Arizona", file: "ArizonaPlate.tsx", sample: "ABC1234" },
  CA: { name: "California", file: "CaliforniaPlate.tsx", sample: "1ABC234" },
  CO: { name: "Colorado", file: "ColoradoPlate.tsx", sample: "ABC123" },
  CT: { name: "Connecticut", file: "ConnecticutPlate.tsx", sample: "AB12345" },
  DC: { name: "District of Columbia", file: "DistrictofColumbiaPlate.tsx", sample: "AB1234" },
  DE: { name: "Delaware", file: "DelawarePlate.tsx", sample: "123456" },
  FL: { name: "Florida", file: "FloridaPlate.tsx", sample: "ABC234" },
  GA: { name: "Georgia", file: "GeorgiaPlate.tsx", sample: "ABC1234" },
  HI: { name: "Hawaii", file: "HawaiiPlate.tsx", sample: "ABC123" },
  IA: { name: "Iowa", file: "IowaPlate.tsx", sample: "ABC123" },
  ID: { name: "Idaho", file: "IdahoPlate.tsx", sample: "1A12345" },
  IL: { name: "Illinois", file: "IllinoisPlate.tsx", sample: "AB12345" },
  IN: { name: "Indiana", file: "IndianaPlate.tsx", sample: "123ABC" },
  KS: { name: "Kansas", file: "KansasPlate.tsx", sample: "1234ABC" },
  KY: { name: "Kentucky", file: "KentuckyPlate.tsx", sample: "ABC123" },
  LA: { name: "Louisiana", file: "LouisianaPlate.tsx", sample: "123ABC" },
  MA: { name: "Massachusetts", file: "MassachusettsPlate.tsx", sample: "1ABC23" },
  MD: { name: "Maryland", file: "MarylandPlate.tsx", sample: "1AB2345" },
  ME: { name: "Maine", file: "MainePlate.tsx", sample: "1234AB" },
  MI: { name: "Michigan", file: "MichiganPlate.tsx", sample: "ABC1234" },
  MN: { name: "Minnesota", file: "MinnesotaPlate.tsx", sample: "ABC123" },
  MO: { name: "Missouri", file: "MissouriPlate.tsx", sample: "AB1C2D" },
  MS: { name: "Mississippi", file: "MississippiPlate.tsx", sample: "ABC123" },
  MT: { name: "Montana", file: "MontanaPlate.tsx", sample: "123456A" },
  NC: { name: "North Carolina", file: "NorthCarolinaPlate.tsx", sample: "ABC1234" },
  ND: { name: "North Dakota", file: "NorthDakotaPlate.tsx", sample: "123ABC" },
  NE: { name: "Nebraska", file: "NebraskaPlate.tsx", sample: "ABC123" },
  NH: { name: "New Hampshire", file: "NewHampshirePlate.tsx", sample: "1234567" },
  NJ: { name: "New Jersey", file: "NewJerseyPlate.tsx", sample: "ABC12D" },
  NM: { name: "New Mexico", file: "NewMexicoPlate.tsx", sample: "ABC123" },
  NV: { name: "Nevada", file: "NevadaPlate.tsx", sample: "123A45" },
  NY: { name: "New York", file: "NewYorkPlate.tsx", sample: "ABC1234" },
  OH: { name: "Ohio", file: "OhioPlate.tsx", sample: "ABC1234" },
  OK: { name: "Oklahoma", file: "OklahomaPlate.tsx", sample: "ABC123" },
  OR: { name: "Oregon", file: "OregonPlate.tsx", sample: "123ABC" },
  PA: { name: "Pennsylvania", file: "PennsylvaniaPlate.tsx", sample: "ABC1234" },
  RI: { name: "Rhode Island", file: "RhodeIslandPlate.tsx", sample: "AB123" },
  SC: { name: "South Carolina", file: "SouthCarolinaPlate.tsx", sample: "123ABC" },
  SD: { name: "South Dakota", file: "SouthDakotaPlate.tsx", sample: "1AB234" },
  TN: { name: "Tennessee", file: "TennesseePlate.tsx", sample: "ABC1234" },
  TX: { name: "Texas", file: "TexasPlate.tsx", sample: "ABC1234" },
  UT: { name: "Utah", file: "UtahPlate.tsx", sample: "A123BC" },
  VA: { name: "Virginia", file: "VirginiaPlate.tsx", sample: "ABC1234" },
  VT: { name: "Vermont", file: "VermontPlate.tsx", sample: "ABC123" },
  WA: { name: "Washington", file: "WashingtonPlate.tsx", sample: "ABC1234" },
  WI: { name: "Wisconsin", file: "WisconsinPlate.tsx", sample: "ABC1234" },
  WV: { name: "West Virginia", file: "WestVirginiaPlate.tsx", sample: "1AB234" },
  WY: { name: "Wyoming", file: "WyomingPlate.tsx", sample: "112345" },
} as const satisfies Record<PlateState, { name: string; file: string; sample: string }>;

export const ARTWORK_STATES = Object.keys(PLATE_METADATA) as PlateState[];
