// Photo references for the plate redraws, one entry per state.
//
// Hotlinked rather than copied into the repo — these are dev-only and we don't
// want other people's product photography in git. If one 404s, that state's
// reference column just goes blank.
//
// `image` and `plate` are in source pixels: the image's natural size, and where
// the plate's edges fall inside it. Pixels rather than fractions because that is
// what you actually measure, and because the harness needs the image aspect to
// crop without distorting (source images are not all square).
//
// Prefer official DMV artwork when it is available at a useful resolution.
// Replica product shots are a fallback, but can differ from the issued plate.

export type PlateReference = {
  state: string;
  label: string;
  src: string;
  /** The source image's natural size, in pixels. */
  image: { w: number; h: number };
  /** Where the plate sits inside that image, in source pixels. */
  plate: { x: number; y: number; w: number; h: number };
  /** Sample registrations to render, ideally including the canonical format. */
  samples: string[];
  /** Visual inspection crops in the SVG's 1000 × 500 coordinate space; not scoring masks. */
  details?: { label: string; x: number; y: number; w: number; h: number }[];
  notes?: string;
};

/**
 * Extra states the comparator should score beyond the bespoke components. Empty
 * now that every jurisdiction has one; a reference alone is not enough anyway,
 * since scoring also needs a profile in tools/artwork/comparison/compare.tsx.
 */
export const SPEC_SCORED_STATES = [] as const;

export const PLATE_REFERENCES: PlateReference[] = [
  {
    state: "NY",
    label: "New York — Excelsior (2020–)",
    src: "https://dmv.ny.gov/sites/default/files/styles/wysiwyg/public/images/2021-11/excelsior_embossed_plate_3d_master.jpg?itok=KFMjdJB0",
    image: { w: 660, h: 343 },
    plate: { x: 9, y: 9, w: 642, h: 324 },
    samples: ["ABC1234", "AB***34", "PA*K1"],
    notes:
      "Official NY DMV Excelsior reference. Niagara's uneven spillway, pale Adirondack ridges, Liberty's raised torch, the navy skyline, and Montauk's beacon follow the lower edge. State name is a high-contrast serif; motto is an outlined Clarendon-style slab. Compare the inset border, mounting slots, and embossed serial as well as the scenery.",
  },
  {
    state: "CA",
    label: "California — white base (1998–)",
    src: "https://signsandtagsonline.com/cdn/shop/products/california-custom-license-plate-1234567890-red-text-white.jpg?v=1736861799&width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 97, y: 348, w: 1007, h: 508 },
    samples: ["1ABC234", "1***234", "LA*56", "CALIFORNIA"],
    notes:
      "White script base with a wide red brush wordmark and trailing swash, navy serial, red URL, and shaded mounting slots. The novelty reference has a ten-digit serial; the app retains canonical and anonymized formatting. Artwork scores measure the rim and slots; inspect lettering in the browser.",
  },
  {
    state: "NJ",
    label: "New Jersey — Garden State (yellow fade)",
    src: "https://signsandtagsonline.com/cdn/shop/products/g-personalized-new-jersey-state-license-plate.jpg?v=1736863332&width=1946",
    image: { w: 1000, h: 776 },
    plate: { x: 99, y: 185, w: 805, h: 408 },
    samples: ["ABC12D", "NJ*45X", "T99ZZ1", "CUSTOM12345"],
    notes:
      "Garden State yellow-to-white base, dark recessed mounting slots and the state separator placed between the serial groups. The reference is a novelty sample; browser lettering remains separate from artwork scoring. The SVG uses per-instance resources and constrains long registrations.",
  },
  {
    state: "PA",
    label: "Pennsylvania — visitPA.com",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/pennsylvania-state-auto-tag-any-text.jpg?v=1588190239&width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 95, y: 347, w: 1011, h: 505 },
    samples: ["ABC1234", "PA*99X", "KEYSTONE123"],
    notes: "visitPA.com base with a shaded navy header, yellow footer, pressed rim and rounded keystone. Upper and lower mounting slots have distinct shading; serials have a subtle embossed edge, with long registrations kept vertically centred. The novelty reference's typography differs from issued plates.",
  },
  {
    state: "MA",
    label: "Massachusetts — Spirit of America",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/w-custom-massachusetts-license-plate.jpg?v=1575473284&width=1946",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1011, "h": 505},
    samples: ["1ABC23", "MA*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. Red serial with narrower blue italic serif lettering for the state name and Spirit of America motto. County/month/year decals remain unassigned. The reference’s FEB and dated sticker are vehicle-specific, so the app leaves them unassigned.",
  },
  {
    state: "CT",
    label: "Connecticut — Constitution State",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/connecticut-any-text-license-plate.jpg?v=1588160969&width=1946",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1011, "h": 505},
    samples: ["AB12345", "CT*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. Blue-to-white fade, navy rule and Connecticut outline, with regular-weight serif lettering and separately fitted state-name and motto widths. County/month/year decals remain unassigned.",
  },
  {
    state: "VT",
    label: "Vermont — Green Mountain State",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/vermont-custom-license-plate.jpg?v=1588872449&width=1946",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 94, "y": 346, "w": 1011, "h": 505},
    samples: ["ABC123", "VT*99X", "CUSTOM12345"],
    notes: "Green Mountain State base with a silver-white serial frame, branched sugar maple, serif wordmark and pressed motto panel. The novelty photo's reflective grain, seller marks and sample lettering differ from issued plates; the SVG preserves editable artwork and does not copy photographic surface noise or assign vehicle decals.",
  },
  {
    state: "NH",
    label: "New Hampshire — Old Man of the Mountain",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/files/custom-text-new-hampshire-novelty-flat-license-plate.jpg?v=1718202049&width=1946",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 94, "y": 346, "w": 1011, "h": 505},
    samples: ["1234567", "NH*99X", "CUSTOM12345"],
    notes: "Old Man of the Mountain base with a stepped brow, nose, lips and chin, irregular granite fissures and pale strata. The split New / Hampshire footer has broader script and taller serif lettering. The source-specific serial masks preserve the profile between groups. Fine granite texture and exact lettering remain simplified.",
  },
  {
    state: "RI",
    label: "Rhode Island — Wave / Ocean State",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/rhode-island-custom-license-plate-any-text.jpg?v=1588871005&width=1946",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 94, "y": 346, "w": 1011, "h": 505},
    samples: ["AB123", "RI*99X", "CUSTOM12345"],
    notes: "Wave / Ocean State base with a connected curling wave, a detailed anchor and an empty lower-right decal well. State and motto use tall regular-weight serif lettering. The full wave curl is exposed by the source-specific serial masks. Novelty reference lettering and reflective texture differ from issued plates.",
  },
  {
    state: "IL",
    label: "Illinois — Land of Lincoln",
    src: "https://signsandtagsonline.com/cdn/shop/products/illinois-lincoln-custom-text-license-plate.jpg?v=1649959516&width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 96, y: 348, w: 1008, h: 504 },
    samples: ["AB12345", "IL*99X"],
    notes: "Land of Lincoln base: cropped grayscale Lincoln portrait and coat, white Chicago skyline, a spoked farm windmill with open lattice legs, and Springfield Capitol, blue-to-white sky, red serial, and black serif lettering. This novelty reference clarifies the artwork; its ANY TEXT serial and REPLICA watermark are excluded from scoring.",
  },
  {
    state: "OH",
    label: "Ohio — Birthplace of Aviation",
    src: "https://signsandtagsonline.com/cdn/shop/files/custom-text-new-ohio-license-plate-any-text.jpg?v=1690472426&width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 96, y: 348, w: 1008, h: 504 },
    samples: ["ABC1234", "OH*99X"],
    notes: "Sunrise in Ohio: periwinkle sky and sunbeams, skyline, rolling hills, river, wheat, and an oak with a swing, child, and dog. A Wright Flyer trails the folded red slogan ribbon beside the Ohio outline. The reference's ANY TEXT lettering is excluded from artwork scoring.",
  },
  {
    state: "GA",
    label: "Georgia — Peach State",
    src: "https://signsandtagsonline.com/cdn/shop/files/custom-text-georgia-peach-state-novelty-license-plate.jpg?v=1700498500&width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 96, y: 348, w: 1008, h: 504 },
    samples: ["ABC1234", "GA*99X"],
    notes: "Peach Orchard base: flowering tree at left, shaded fruit, receding orchard rows and a blue-to-white-to-peach sky. Simplified bark, peach-blush and distant-tree contours refine the illustration. The county decal stays blank because the app has no county data. The reference serial and county lettering are excluded from artwork scoring.",
  },
  {
    state: "MD",
    label: "Maryland — Maryland Proud",
    src: "https://signsandtagsonline.com/cdn/shop/products/custom-maryland-state-license-plate.jpg?v=1588179681&width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 94, y: 347, w: 1012, h: 506 },
    samples: ["1AB2345", "MD*99X"],
    notes: "Maryland Proud base: off-white field, red calligraphic wordmark with a curled capital M and italic serif lowercase, black serial, and a softly faded, waving state flag. The flag alternates Calvert's black-and-gold pattern with Crossland's red-and-white crosses. The reference's ten-digit serial is excluded from artwork scoring; the lower flag remains measured.",
  },
  {
    state: "VA",
    label: "Virginia — Virginia is for Lovers",
    src: "https://signsandtagsonline.com/cdn/shop/files/40001-VA-2.jpg?v=1781701743&width=1946",
    image: {"w": 1500, "h": 1500},
    plate: {"x": 118, "y": 433, "w": 1264, "h": 632},
    samples: ["ABC1234", "VA*99X", "CUSTOM12345"],
    notes: "White passenger base with a narrower blue serif state name, pressed rim, recessed mounting slots and a compact Virginia is for Lovers footer with its red heart. The seller substitutes Love the land. Love Virginia.; the SVG retains the selected Virginia is for Lovers design, checked against the Virginia DMV passenger standard issue example.",
  },
  {
    state: "MI",
    label: "Michigan — Pure Michigan",
    src: "https://signsandtagsonline.com/cdn/shop/products/custom-michigan-state-license-plate.jpg?v=1588090258&width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 94, y: 347, w: 1012, h: 506 },
    samples: ["ABC1234", "MI*99X", "MICHIGAN123"],
    notes: "Pure Michigan base with an open brush M, spaced blue lettering, and a curved blue footer carrying michigan.org in white. The reflective rim, rounded band corners, mounting slots, and subtle serial embossing follow the reference. The seller’s centre watermark and tiny URL are not part of the plate.",
  },
  {
    state: "FL",
    label: "Florida — Sunshine State (2019–)",
    src: "https://florida-license-plate.com/cdn/shop/files/2019-2024-florida-license-plate-sunshine-state.png?v=1713875604&width=1946",
    image: { w: 1771, h: 900 },
    plate: { x: 12, y: 13, w: 1745, h: 879 },
    samples: ["ABC234", "ZO**99", "MI**21", "SUNSHINE"],
    notes:
      "Sunshine State base with a fine screened Florida silhouette, overlapping oranges, curved leaf sprays, and irregular white blossoms. Green serial and condensed motto have a subtle embossed shadow. Mounting holes and an unassigned decal well sit inside the pressed rim; MYFLORIDA.COM follows the top arc.",
  },
  {
    state: "LA",
    label: "Louisiana — Sportsman's Paradise (pelican)",
    src: "https://signsandtagsonline.com/cdn/shop/products/louisiana-customized-license-plate.jpg?width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 95, y: 347, w: 1010, h: 507 },
    samples: ["123ABC", "LA*99X", "PELICAN123"],
    notes: "Pelican base: ivory sky fading through cream to salmon, red Louisiana script, and Sportsman’s Paradise at lower left. A brown pelican has a long bill, pale pouch, layered wing and breast feathers, and webbed feet on a weathered piling. Its black inset border, mounting slots, and blank lower-right decal well follow the reference.",
  },
  {
    state: "MO",
    label: "Missouri — Show Me State (bluebird)",
    src: "https://signsandtagsonline.com/cdn/shop/products/missouri-any-text-license-plate.jpg?width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 95, y: 347, w: 1010, h: 507 },
    samples: ["AB1C2D", "MO*99X", "BLUEBIRD123"],
    notes: "Bluebird Show Me State base: pale grey fading to blue, Missouri outline with the Mississippi River bends and Bootheel, and an eastern bluebird perched on flowering hawthorn. Shaded mounting slots and a pressed rim frame the navy serial. The reference's MAR month is omitted because no registration month is supplied.",
  },
  {
    state: "MT",
    label: "Montana — Treasure State (blue)",
    src: "https://signsandtagsonline.com/cdn/shop/products/montana-any-text-license-plate2.jpg?width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 95, y: 347, w: 1010, h: 507 },
    samples: ["123456A", "MT*99X", "BIGSKY123"],
    notes: "Blue 2010 base: white Montana outline with its irregular Idaho border, buffalo-skull separator, TREASURE STATE header, and MONTANA - 10 footer. Shaded mounting slots and an unassigned upper-right decal well complete the rim. The novelty reference uses ANY TEXT; registrations retain their supplied characters.",
  },
  {
    state: "NV",
    label: "Nevada — Home Means Nevada (2021–)",
    src: "https://signsandtagsonline.com/cdn/shop/products/nevada-customized-state-license-plate.jpg?width=1946",
    image: { w: 1200, h: 1200 },
    plate: { x: 95, y: 347, w: 1010, h: 507 },
    samples: ["123A45", "NV*99X", "CUSTOM12345"],
    notes: "Home Means Nevada base with a faceted desert, snow-capped peaks and a black state separator. Slab-serif state and motto lettering follow the reference more closely; custom and anonymized registrations have bounded widths. Novelty lettering and photographic surface effects remain approximation limits.",
  },
  {
    state: "TX",
    label: "Texas — Texas Classic (2012–)",
    src: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Texas_Passenger_Car_License_Plate_2020.png",
    image: { w: 1328, h: 671 },
    plate: { x: 6, y: 6, w: 1316, h: 658 },
    samples: ["ABC1234", "LHD8448", "TX*99X", "LONESTAR123"],
    notes:
      "Texas Classic with a faceted five-point star, Texas silhouette separator, flat black lettering, pressed rim, mounting slots and two subtle vertical security threads. The issued reference photo has surface wear, fitted screws and a vehicle-specific barcode; those are not reproduced. The Texas separator remains visible for blank, short, custom and anonymized registrations; all supplied characters are preserved in groups with room for the symbol.",
  },
  {
    state: "AL",
    label: "Alabama — Beach sunrise (2022)",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/files/custom-text-alabama-novelty-license-plate-1.jpg?v=1690476081",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["1AB2345", "AL*99X", "CUSTOM12345"],
    notes: "Beach sunrise base with layered Gulf clouds, dunes, sea oats and Heart of Dixie. The bright sun is restored above the water and the travel URL has a wider italic setting. Cloud banks have irregular rounded edges, pale highlights and rose shadows, with warm sky between the rising plumes. Novelty photo typography and reflective grain differ from issued plates.",
  },
  {
    state: "AK",
    label: "Alaska — Gold / The Last Frontier",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/personalized-alaska-license-plate.jpg?v=1588159105",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC123", "AK*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. Gold field with a blue flag and eight star cutouts, redrawn as editable contours at the reference proportions and position. County/month/year decals remain unassigned.",
  },
  {
    state: "AZ",
    label: "Arizona — Grand Canyon State",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/61UoA24pjML._SL1200.jpg?v=1588097759",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC1234", "AZ*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. Turquoise-to-sunset field, purple desert mountains and a saguaro with reference-guided arms and trunk contours. Fine background details and lettering remain approximate. County/month/year decals remain unassigned.",
  },
  {
    state: "AR",
    label: "Arkansas — The Natural State / diamond",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/arkansas-custom-text-license-plate.jpg?v=1588159643",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC12D", "AR*99X", "CUSTOM12345"],
    notes: "Natural State diamond base with a centered, faceted silver gem, restrained facet gradients and recessed mounting slots. The red state name is taller and narrower, and the footer uses a larger serif. Complete source wordmark and serial masks expose the gem between groups. Vehicle decals remain unassigned.",
  },
  {
    state: "CO",
    label: "Colorado — Green mountain base",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/colorado-any-text-license-plate.jpg?v=1588160079",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC123", "CO*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. Reference-fitted Rocky Mountain summits, broken rock-shadow contours that taper and fade into the snowfield, and a dark green inset rim. The former horizontal cutoff is removed. Serial relief is excluded from the artwork contours. Lettering remains approximate; county/month/year decals remain unassigned.",
  },
  {
    state: "DE",
    label: "Delaware — The First State",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/delaware-any-text-custom-license-plate.jpg?v=1588161734",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["123456", "DE*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography differs from issued plates. Navy field, gold frame and gold lettering, with the mounting recesses positioned to the reference. Lettering is reviewed separately in the browser. County/month/year decals remain unassigned.",
  },
  {
    state: "DC",
    label: "District of Columbia — End Taxation Without Representation",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/dc-customized-license-plate.jpg?v=1594300420",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["AB1234", "DC*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. Red rules and three-star/two-bar flag separator. Refined flag proportions, red rules and condensed footer. Typography remains an approximation. County/month/year decals remain unassigned.",
  },
  {
    state: "HI",
    label: "Hawaii — Rainbow / Aloha State",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/hawaii-any-text-custom-license-plate.jpg?v=1588173008",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC123", "HI*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography differs from issued plates. Soft magenta, yellow and blue circular rainbow arcs fitted to the visible printed colors, with recessed mounting slots. Lettering is reviewed separately in the browser. County/month/year decals remain unassigned.",
  },
  {
    state: "ID",
    label: "Idaho — Scenic Idaho / Famous Potatoes",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/scenic-idaho-custom-text-license-plate.jpg?v=1588173886",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["1A12345", "ID*99X", "CUSTOM12345"],
    notes: "Scenic Idaho / Famous Potatoes base with fine handwritten Scenic strokes and bold upright Idaho serif lettering, a red header fade, broken snow gullies and an uneven navy fir canopy. The footer uses upright serif lettering fitted between the mounting slots. The reference is a novelty photo; exact lettering and reflective surface grain remain approximate.",
  },
  {
    state: "IN",
    label: "Indiana — Covered bridge",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/customized-indiana-state-license-plate.jpg?v=1588176156",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["123ABC", "IN*99X", "CUSTOM12345"],
    notes: "Covered bridge base with blue sky, layered foliage and an unassigned county decal. The taller, narrower Indiana name and raised registration leave more room for the bridge and river. The bridge has a pale overhanging roof, open trusses, siding, dark windows and stone piers. Split rail fences, creek ripples, tree branches and two birds complete the scene. Novelty sample lettering and the numbered decal are excluded from scoring.",
  },
  {
    state: "IA",
    label: "Iowa — Skyline and fields",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/iowa-state-custom-license-plate-any-text.jpg?v=1588883957",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC123", "IA*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. Urban and rural skyline, wind turbine and grass. Refined inset cyan/green frame, skyline field and grass height. Fine skyline details remain simplified. County/month/year decals remain unassigned.",
  },
  {
    state: "KS",
    label: "Kansas — To the Stars (2024)",
    src: "https://www.ksrevenue.gov/img/newplate.png",
    image: {"w": 1643, "h": 833},
    plate: {"x": 1, "y": 3, "w": 1640, "h": 824},
    samples: ["1234ABC", "KS*99X", "CUSTOM12345"],
    notes: "Official Kansas DOR To the Stars sample. State-shaped charcoal frame, blue-to-gold field, Capitol dome with Ad Astra archer, circular mounting holes and blank decal panels. Condensed heading and serial, with the registration kept clear of the Capitol; script motto uses the app's closest available font. County/month/year decals remain unassigned.",
  },
  {
    state: "KY",
    label: "Kentucky — Bluegrass State",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/custom-text-kentucky-bluegrass-state-novelty-licesnse-plate.jpg?v=1617136296",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC123", "KY*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. State silhouette and layered green hills. Refined state outline, soft layered hills, blank county well and asymmetric white rim. Scenic edge F1 remains below the saved baseline despite improved similarity and SSIM. County/month/year decals remain unassigned.",
  },
  {
    state: "ME",
    label: "Maine — Chickadee / Vacationland",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/maine-any-text-custom-license-plate.jpg?v=1588178917",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["1234AB", "ME*99X", "CUSTOM12345"],
    details: [
      { label: "Chickadee", x: 22, y: 36, w: 150, h: 225 },
      { label: "Pinecone", x: 43, y: 250, w: 112, h: 175 },
    ],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. The chickadee has a buff flank, tapered wing shading and no exterior photo halo. The pinecone’s overlapping buff and orange scales follow the reference positions, with curved lips and restrained outlines. Both pixel and shape agreement improve over the first simplification pass. Inspect the close-ups as well as card sizes. Lettering and fine feather detail remain approximations; county/month/year decals remain unassigned.",
  },
  {
    state: "MN",
    label: "Minnesota — Explore Minnesota / 10,000 lakes",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/minnesota-customized-license-plate.jpg?v=1588180106",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC123", "MN*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. Lake, northern trees and state outline. Refined lake shore, distant trees, canoe and state separator. Registrations reserve the off-center symbol; fine tree details remain simplified. County/month/year decals remain unassigned.",
  },
  {
    state: "MS",
    label: "Mississippi — Magnolia (2024)",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/files/custom-text-mississippi-2024-present-flower-novelty-license-plate.jpg?v=1723032727",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC123", "MS*99X", "CUSTOM12345"],
    notes: "Magnolia base with a navy circular medallion, overlapping cupped petals, fine veins and a gold center. Decorative wordmark swashes and a shaded pressed rim follow the reference; serial groups reserve the full flower. County remains unassigned, without inventing a printed decal box. Novelty serial, county lettering and complete wordmark are excluded from artwork scoring.",
  },
  {
    state: "NE",
    label: "Nebraska — Genius of Creative Energy (2023)",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/files/custom-text-nebraska-novelty-license-plate-1.jpg?v=1714485289",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC123", "NE*99X", "CUSTOM12345"],
    notes: "Creative Energy mosaic base with a seated figure, lightning, flowing drapery and curling waves in pale silver inks. The navy outline follows the inset mural panel, with a gap beneath the bold state name. Nebraska DMV's 2023–2029 series sheet confirms the selected mural base. The novelty reference's year and serial are excluded; vehicle decals remain unassigned.",
  },
  {
    state: "NM",
    label: "New Mexico — Turquoise centennial / Zia",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/files/custom-text-new-mexico-centennial-blue-nvelty-license-plate-1.jpg?v=1690566169",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC123", "NM*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; the source serial says ANY TXT. Turquoise Centennial base with connected, rounded Zia rays, a red center and a raised yellow rim. Comparison masks expose the complete Zia while excluding the six serial glyphs and their relief. Lettering remains approximate. County/month/year decals remain unassigned.",
  },
  {
    state: "NC",
    label: "North Carolina — First in Flight",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/files/personalized-text-north-carolina-first-in-flight-licesne-plate.jpg?v=1683838709",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC1234", "NC*99X", "CUSTOM12345"],
    notes: "First in Flight base with the existing Wright Flyer bracing, windblown grass and sand. Taller red heading and state lettering, plus a lightly outlined blue serial, better match the reference proportions at browser sizes. Artwork is retained; novelty typography and photographic relief remain approximation limits.",
  },
  {
    state: "ND",
    label: "North Dakota — Legendary / bison sunset",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/custom-text-north-dakota-peace-garden-state-license-plate.jpg?v=1617234167",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["123ABC", "ND*99X", "CUSTOM12345"],
    notes: "Badlands sunrise, layered rock faces, shaded bison, wheat and outlined North Dakota heading; Peace Garden State sits at bottom left. Cross-checked against NDDOT's official sample. The scored novelty photo has different mounting slots, surface grain and sample lettering; its unassigned sticker panel is retained without copying a vehicle's decal. Refined western sunset shadows over the Badlands, wheat and bison. Fine fur and lettering remain approximate.",
  },
  {
    state: "OK",
    label: "Oklahoma — Imagine That (2024)",
    src: "https://oklahoma.gov/ltgovpinnell/newsroom/2024/august/lt--governor-pinnell-and-service-oklahoma-announce-new-license-p/_jcr_content/responsivegrid/image_1418973381.coreimg.png/1723150079989/plate-final.png",
    image: {"w": 1024, "h": 519},
    plate: {"x": 5, "y": 5, "w": 1014, "h": 509},
    samples: ["ABC123", "OK*99X", "CUSTOM12345"],
    notes: "Red Imagine That base with a white star and 46, bison, wind turbine, scissortail, oil derricks and rancher silhouettes. The small crescent, stars and motto emblem complete the footer. Registration groups leave the central star clear. Month/year decals remain unassigned; the photo is a novelty sample.",
  },
  {
    state: "OR",
    label: "Oregon — Douglas fir",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/oregon-custom-license-plate.jpg?v=1588190058",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["123ABC", "OR*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography differs from issued plates. Snow-edged Douglas fir with irregular branch contours; branches obscured by the sample serial are completed from the visible opposite side. The lower fir stands follow simplified reference contours. Mountain ridge and lettering remain approximate. County/month/year decals remain unassigned.",
  },
  {
    state: "SC",
    label: "South Carolina — Revolutionary War (2026)",
    src: "https://dmv.sc.gov/sites/scdmv/files/inline-images/RP4%20Plate.png",
    image: {"w": 1065, "h": 538},
    plate: {"x": 11, "y": 12, "w": 1040, "h": 516},
    samples: ["123ABC", "SC*99X", "CUSTOM12345"],
    notes: "Official agency sample. Liberty flag and soldier vignette. Refined cyan rim, round holes, top rule and blank decal panel. Soldier and flag details remain simplified; printer barcode and sample labels are excluded from artwork scoring. County/month/year decals remain unassigned.",
  },
  {
    state: "SD",
    label: "South Dakota — Mount Rushmore",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/south-dakota-custom-state-license-plate.jpg?v=1588870851",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["1AB234", "SD*99X", "CUSTOM12345"],
    notes: "Great Faces. Great Places. base with four distinct Rushmore profiles and irregular granite planes in three restrained inks. Condensed footer lettering and a narrower script state name preserve the selected scenic design. The source-specific masks exclude the complete novelty serial and footer without hiding the faces between the groups. Fine rock texture is simplified.",
  },
  {
    state: "TN",
    label: "Tennessee — Blue / Volunteer State (2022)",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/files/custom-text-new-tennessee-license-plate-any-text2.jpg?v=1690207980",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC1234", "TN*99X", "CUSTOM12345"],
    notes: "Blue Volunteer State base with an accurately inset rim, Tennessee outline, repositioned tristar medallion and blank county panel. The narrower state name and spaced travel URL fit their printed fields. Source-specific masks exclude the complete serial, optional curved motto, county and seller marks while exposing the state outline and medallion. County remains unassigned.",
  },
  {
    state: "UT",
    label: "Utah — Delicate Arch / Life Elevated",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/utah-state-license-plate-any-text.jpg?v=1588872211",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["A123BC", "UT*99X", "CUSTOM12345"],
    notes: "Life Elevated arch base with weathered sandstone shadow ledges, a red pedestal and pale distant mountains. The state name uses a heavier outlined slab serif and the footer is widely spaced with a white outline. This preserves the selected arch design; the novelty photo's serial and surface effects are excluded or simplified.",
  },
  {
    state: "WA",
    label: "Washington — Mount Rainier / Evergreen State",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/files/custom-text-washington-state-replica-license-plate.jpg?v=1683902177",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC1234", "WA*99X", "CUSTOM12345"],
    notes: "Evergreen State base with broken Mount Rainier snowfields and connected blue ridges. The red state name is left-aligned and the footer is wider; a continuous lower blue field prevents reference lettering from becoming snow cutouts. The novelty sample's serial and lettering relief are excluded from scoring.",
  },
  {
    state: "WV",
    label: "West Virginia — Wild, Wonderful",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/wes-virginia-custom-license-plate.jpg?v=1589303125",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["1AB234", "WV*99X", "CUSTOM12345"],
    notes: "Novelty photo reference; sample typography and seller watermarks differ from issued plates. Navy header, gold rules and faint central seal. Refined rounded navy header, gold/navy footer rules and seal placement. Seal details remain simplified. County/month/year decals remain unassigned.",
  },
  {
    state: "WI",
    label: "Wisconsin — America’s Dairyland",
    src: "https://cdn.shopify.com/s/files/1/0267/1643/8599/products/wisconsin-custom-license-plate-any-text.jpg?v=1588875276",
    image: {"w": 1200, "h": 1200},
    plate: {"x": 95, "y": 347, "w": 1012, "h": 506},
    samples: ["ABC1234", "WI*99X", "CUSTOM12345"],
    notes: "America's Dairyland base with a condensed italic red state name and motto, tree-covered hills and a compact barn vignette above the navy rule. The original physical border and slots remain. The novelty photo's serial, typography and reflective grain differ from issued plates.",
  },
  {
    state: "WY",
    label: "Wyoming — Flag / bucking horse (2025)",
    src: "https://dot.state.wy.us/files/live/sites/wydot/files/shared/Motor%20Vehicle%20Services/2025%20Plate%20images/2025-4-DIGIT-PASS.jpg",
    image: {"w": 846, "h": 430},
    plate: {"x": 7, "y": 6, "w": 832, "h": 418},
    samples: ["112345", "WY*99X", "CUSTOM12345"],
    notes: "Official agency sample. Flag border, corrected bison silhouette, seal engraving and reference-guided bucking horse and rider contours. The seal remains simplified where obscured by the sample serial. Vehicle-specific decals remain unassigned; typography is reviewed separately in the browser.",
  },
];
