import { readdir, writeFile } from "node:fs/promises";
import potrace from "potrace";
import sharp from "sharp";
import { components } from "./artwork/bitmap.ts";
import { fetchSource, loadSources, rasterise } from "./artwork/traces/source.ts";

// Fixed lettering traced from full-resolution official artwork, where a font cannot match the plate.
// Each state's source is configured in tools/artwork/traces/<state>.ts, fetched and checksum-pinned here; no image
// is committed. Usage: bun run tools/trace-lettering.ts [--states=NY,TX]
const only = process.argv.find((arg) => arg.startsWith("--states="))?.slice(9).toLowerCase().split(",");
const configs = (await readdir(new URL("./artwork/traces/", import.meta.url))).filter((file) => /^[a-z]{2}\.ts$/.test(file))
  .map((file) => file.slice(0, 2)).filter((state) => !only || only.includes(state));

for (const state of configs) {
  const sources = await loadSources(state);
  const exports = [];
  for (const source of sources) {
    const bytes = await fetchSource(source);
    const { data, info } = await sharp(await rasterise(bytes, source.render)).flatten({ background: "#fff" }).removeAlpha().raw().toBuffer({ resolveWithObject: true });
    const { plate } = source;
    const toPlate = (px: number, py: number) => [(px - plate.x) * 1000 / plate.width, (py - plate.y) * 500 / plate.height] as const;
    const toImage = (x: number, y: number) => [Math.round(plate.x + x * plate.width / 1000), Math.round(plate.y + y * plate.height / 500)] as const;

    for (const { name, doc, box, ink, minArea = 8, smooth } of source.traces) {
      const [left, top] = toImage(box.x0, box.y0), [right, bottom] = toImage(box.x1, box.y1);
      const width = right - left, height = bottom - top;
      const pixels = new Uint8Array(width * height);
      for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) {
        const i = ((top + y) * info.width + left + x) * info.channels;
        pixels[y * width + x] = Number(ink([data[i]!, data[i + 1]!, data[i + 2]!]));
      }
      // Neighbouring artwork that crosses the box edge (trees, landmarks, registration glyphs) is not this lettering.
      const parts = components({ pixels, width, height });
      const largest = Math.max(0, ...parts.map((c) => c.points.length));
      const kept = parts.filter((c) => c.x > 0 && c.y > 0 && c.x + c.width < width && c.y + c.height < height && c.points.length > largest * .002);
      if (!kept.length) throw new Error(`${state} ${name}: no ink inside its box`);
      const mask = Buffer.alloc(width * height, 255);
      for (const c of kept) for (const p of c.points) mask[p] = 0;
      // Speckle, smoothing and curve tolerances are in source pixels, so scale them with the source's resolution.
      const scale = plate.width / 1000;
      let png = await sharp(mask, { raw: { width, height, channels: 1 } }).png().toBuffer();
      // sharp thresholds before blurring within one pipeline, so blur in its own pass; 128 keeps the edge where it was.
      if (smooth) png = await sharp(await sharp(png).blur(smooth * scale).png().toBuffer()).threshold(128).png().toBuffer();
      const svg = await new Promise<string>((resolve, reject) => potrace.trace(png, { turdSize: Math.round(minArea * scale * scale), alphaMax: 1, optCurve: true, optTolerance: .2, threshold: 128 },
        (error: Error | null, output: string) => error ? reject(error) : resolve(output)));
      // potrace emits absolute coordinate pairs; map each into plate units.
      let index = 0, pending = 0;
      const d = svg.match(/ d="([^"]+)"/)![1]!.replace(/-?\d+(?:\.\d+)?/g, (n) => {
        if (index++ % 2 === 0) { pending = Number(n); return ""; }
        const [x, y] = toPlate(left + pending, top + Number(n));
        return `${x.toFixed(1)} ${y.toFixed(1)}`;
      }).replace(/\s+/g, " ").replace(/ ?([MCLZ]) ?/g, "$1").replace(/ ,/g, ",").trim();
      if (index % 2) throw new Error(`${state} ${name}: odd coordinate count`);
      console.log(`${state.toUpperCase()} ${name}: ${kept.length} components, ${d.length} bytes`);
      exports.push(`/** ${doc}. */\nexport const ${name} = ${JSON.stringify(d)};`);
    }
  }

  await writeFile(new URL(`../src/internal/traces/${state}.ts`, import.meta.url), `// Generated by tools/trace-lettering.ts from tools/artwork/traces/${state}.ts; do not edit.
// Traced from ${sources.map((source) => source.url).join(" and ")}, in plate units.

${exports.join("\n\n")}
`);
}
